# Generated by Django 2.1.3 on 2019-01-02 11:06

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('item', s3direct.fields.S3DirectField(help_text='For standards of this website, if you are uploading a photo/video, it must be 800x400 and in jpg,png,jpeg/mp4 format respectively. PLEASE FOLLOW THIS GUIDELINE VERY CAREFULLY.')),
                ('is_photo', models.BooleanField(default=False, help_text='Please specify if this is a photo or not.')),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
            },
        ),
        migrations.CreateModel(
            name='DomainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('position', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'Domain Info',
                'verbose_name_plural': 'Domain Infos',
            },
        ),
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('subtitle', models.TextField()),
                ('background', s3direct.fields.S3DirectField()),
            ],
            options={
                'verbose_name': 'Home Top Text',
                'verbose_name_plural': 'Home Top Text',
            },
        ),
        migrations.CreateModel(
            name='JourneyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('image', s3direct.fields.S3DirectField()),
                ('btn_text', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Journey Text',
                'verbose_name_plural': 'Journey Text',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', s3direct.fields.S3DirectField()),
                ('favicon', s3direct.fields.S3DirectField()),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('url_name', models.CharField(max_length=40)),
                ('position', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'Navbar Item',
                'verbose_name_plural': 'Navbar Items',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('image', s3direct.fields.S3DirectField()),
            ],
        ),
    ]
