# Generated by Django 2.1.3 on 2018-11-06 05:18

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('item', s3direct.fields.S3DirectField()),
                ('is_photo', models.BooleanField(default=False, help_text='Please specify if this is a photo or not.')),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
            },
        ),
        migrations.CreateModel(
            name='DomainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('position', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'Domain Info',
                'verbose_name_plural': 'Domain Infos',
            },
        ),
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('subtitle', models.TextField()),
            ],
            options={
                'verbose_name': 'Home Top Text',
                'verbose_name_plural': 'Home Top Text',
            },
        ),
        migrations.CreateModel(
            name='JourneyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('btn_text', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Journey Text',
                'verbose_name_plural': 'Journey Text',
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('url_name', models.CharField(max_length=40)),
                ('position', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'Navbar Item',
                'verbose_name_plural': 'Navbar Items',
            },
        ),
    ]
