# Generated by Django 2.1.2 on 2018-10-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navitem',
            options={'verbose_name': 'Navbar Item', 'verbose_name_plural': 'Navbar Items'},
        ),
    ]
