# Generated by Django 2.1.3 on 2018-11-06 06:36

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=s3direct.fields.S3DirectField(help_text='For standards of this website, if you are uploading a photo/video, it must be 800x400 and in jpg,png,jpeg/mp4 format respectively. PLEASE FOLLOW THIS GUIDELINE VERY CAREFULLY.'),
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
