# Generated by Django 2.1.2 on 2018-10-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_auto_20181020_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
