# Generated by Django 2.1.3 on 2018-11-11 09:27

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_auto_20181106_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometext',
            name='background',
            field=s3direct.fields.S3DirectField(default=''),
            preserve_default=False,
        ),
    ]
