# Generated by Django 2.1.2 on 2018-10-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_navitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
