# Generated by Django 2.1.3 on 2018-11-18 10:37

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_hometext_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('image', s3direct.fields.S3DirectField()),
            ],
        ),
    ]
