# Generated by Django 2.1.2 on 2018-10-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_auto_20181020_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='url_name',
            field=models.CharField(max_length=40),
        ),
    ]
