# Generated by Django 2.1.3 on 2018-11-19 10:34

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_objective_objectivetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', s3direct.fields.S3DirectField()),
            ],
        ),
    ]
