# Generated by Django 2.1.3 on 2018-11-19 11:02

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='favicon',
            field=s3direct.fields.S3DirectField(default=''),
            preserve_default=False,
        ),
    ]
