# Generated by Django 2.1.2 on 2018-10-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_hometext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='body',
            field=models.TextField(),
        ),
    ]
