# Generated by Django 2.1.2 on 2018-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0007_auto_20181021_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometext',
            name='subtitle',
            field=models.TextField(default='ABCD'),
            preserve_default=False,
        ),
    ]
