# Generated by Django 2.1.2 on 2018-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0008_hometext_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(height_field=400, upload_to='media/images/', width_field=800)),
            ],
        ),
    ]
