# Generated by Django 2.1.2 on 2018-10-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0009_carouselitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'Carousel Item', 'verbose_name_plural': 'Carousel Items'},
        ),
        migrations.AlterModelOptions(
            name='hometext',
            options={'verbose_name': 'Home Top Text', 'verbose_name_plural': 'Home Top Text'},
        ),
    ]
