# Generated by Django 2.1.2 on 2018-10-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0010_auto_20181021_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField(default='')),
                ('image', models.ImageField(height_field=200, upload_to='media/images', width_field=200)),
            ],
            options={
                'verbose_name': 'Journey Text',
                'verbose_name_plural': 'Journey Text',
            },
        ),
    ]
