# Generated by Django 2.1.2 on 2018-10-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0011_journeytext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journeytext',
            options={},
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='image',
            field=models.ImageField(height_field=200, upload_to='media/images/', width_field=200),
        ),
    ]
