# Generated by Django 2.1.2 on 2018-10-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0012_auto_20181021_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
