# Generated by Django 2.1.2 on 2018-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0013_auto_20181021_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journeytext',
            options={'verbose_name': 'Journey Text', 'verbose_name_plural': 'Journey Text'},
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
