# Generated by Django 2.1.2 on 2018-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0014_auto_20181021_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeytext',
            name='btn_text',
            field=models.CharField(default='Next', max_length=10),
            preserve_default=False,
        ),
    ]
