# Generated by Django 2.1.2 on 2018-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0015_journeytext_btn_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('position', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'Domain Info',
                'verbose_name_plural': 'Domain Infos',
            },
        ),
    ]
