# Generated by Django 2.1.2 on 2018-10-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0016_domaintext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='image',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='item',
            field=models.FileField(default='abcd', upload_to='carousel/'),
            preserve_default=False,
        ),
    ]
