# Generated by Django 2.1.2 on 2018-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0017_auto_20181023_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='header',
            field=models.CharField(default='', max_length=255),
        ),
    ]
