# Generated by Django 2.1.2 on 2018-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0018_auto_20181023_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
