# Generated by Django 2.1.2 on 2018-10-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0020_auto_20181023_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometext',
            name='body',
        ),
        migrations.RemoveField(
            model_name='hometext',
            name='header',
        ),
    ]
