# Generated by Django 2.1.2 on 2018-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0022_auto_20181023_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=models.FileField(help_text='This video will take some time to process. Please be patient.', upload_to='carousel/'),
        ),
    ]
