# Generated by Django 2.1.2 on 2018-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0023_auto_20181024_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='is_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=models.FileField(help_text='This image/video will take some time to process. Please be patient.', upload_to='carousel/'),
        ),
    ]
