# Generated by Django 2.1.2 on 2018-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0024_auto_20181024_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='extension',
            field=models.CharField(default='mp4', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=models.FileField(help_text='This image/video will always take some time to process for each save. Please be patient.', upload_to='carousel/'),
        ),
    ]
