# Generated by Django 2.1.2 on 2018-10-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0025_auto_20181024_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='is_photo',
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=models.FileField(help_text='If you are uploading a photo, it must be a png or jpg. If you are uploading a video, it must be 800x400 and in mp4 format.', upload_to='carousel/'),
        ),
    ]
