# Generated by Django 2.1.2 on 2018-10-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0027_carouselitem_is_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='is_photo',
        ),
        migrations.AlterField(
            model_name='hometext',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='header',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='btn_text',
            field=models.CharField(max_length=10),
        ),
    ]
