# Generated by Django 2.1.2 on 2018-10-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0028_auto_20181029_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
    ]
