# Generated by Django 2.1.2 on 2018-10-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0030_auto_20181030_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='is_photo',
            field=models.BooleanField(default=False, help_text='Please specify if this is a photo or not.'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=models.FileField(help_text='For standards of this website, if you are uploading a photo/video, it must be 800x400 and in jpg,png,jpeg/mp4 format respectively. PLEASE FOLLOW THIS GUIDELINE VERY CAREFULLY.', upload_to='carousel/'),
        ),
    ]
