# Generated by Django 2.1.2 on 2018-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0032_auto_20181031_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='item',
            field=models.CharField(help_text='File name. For standards of this website, if you are uploading a photo/video, it must be 800x400 and in jpg,png,jpeg/mp4 format respectively. PLEASE FOLLOW THIS GUIDELINE VERY CAREFULLY.', max_length=255),
        ),
        migrations.AlterField(
            model_name='journeytext',
            name='image',
            field=models.CharField(help_text='File name', max_length=255),
        ),
    ]
